[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.json"]

[phases.build]
cmds = ["php -v", "composer install --no-dev || true"]

[start]
cmd = "php -S 0.0.0.0:8080 -t ."
